### PR TITLE
ci: .travis.yml: use GCC 4.9

### PR DESCRIPTION
**Pull request by jforissier**
Build with GCC 4.9 in order to detect compile errors specific to that
version of the compiler, such as:

  core/tee/tadb.c:593:15: error: missing braces around initializer [-Werror=missing-braces]
    const struct tadb_entry null_entry = { 0 };
                 ^
  core/tee/tadb.c:593:15: error: (near initialization for ‘null_entry.prop’) [-Werror=missing-braces]

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

File: .travis.yml [hunk 1]
```diff
@@ -16,10 +16,13 @@ git:
...
 before_install:
-  # Install the 32-bit cross compiler
-  - wget http://releases.linaro.org/components/toolchain/binaries/5.3-2016.02/arm-linux-gnueabihf/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
-  - tar xf gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
-  - export PATH=${PWD}/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/bin:${PATH}
+  # Install the 32-bit cross compiler. We're using an older version here (4.9)
+  # because some Android setups still use this version which can cause build
+  # errors not caught by later GCC versions, see
+  # https://github.com/OP-TEE/optee_os/issues/1998.
+  - wget http://releases.linaro.org/archive/15.02/components/toolchain/binaries/arm-linux-gnueabihf/gcc-linaro-4.9-2015.02-3-x86_64_arm-linux-gnueabihf.tar.xz
```
Comment (jenswi-linaro) [inline .travis.yml]: This release is a bit old, any reason why this particular release was selected?

Comment (jforissier) [reply .travis.yml]: No particular reason other than it was the one we used previously
```
$ git log --oneline -n 1 -Sgcc-linaro-4.9
0806ea94 Update travis for gcc5
```
I can pick another one though. Maybe the exact one that's used to build AOSP? @vchong?

Comment (jbech-linaro) [reply .travis.yml]: I understand why we are doing this, but it feels like the wrong way to go here, to downgrade the toolchains for all builds. Wouldn't it be better to upgrade to gcc7.x for the majority of the builds and then keep one sanity build using gcc4.9? Sure, we would need to download two toolchains, but I think that could be worth it.

Comment (jenswi-linaro) [reply .travis.yml]: These days this is only a single build. Most of the builds are done in shippable.

Comment (vchong) [reply .travis.yml]: > Maybe the exact one that's used to build AOSP? 

It's here [1], but please note that the actual gcc binary is `real-arm-linux-androideabi-gcc`, not `arm-linux-androideabi-gcc`.

[1] https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/master.tar.gz

**Comment by jforissier** [comment]
It's not so easy to use the Android toolchain: https://travis-ci.org/OP-TEE/optee_os/builds/315454831#L2125-L2141

A random 4.9 GCC should be good enough for our purpose.

**Comment by vchong** [comment]
> It's not so easy to use the Android toolchain: https://travis-ci.org/OP-TEE/optee_os/builds/315454831#L2125-L2141

Right. Looks like the toolchain doesn't come with its own sysroot and in order to get that, we'll have to download the ndk, figure out the Android API level and run each arm-*-gcc command with --sysroot=/path/to/sysroot option. And there's no guarantee that the API level won't change for newer builds/releases.

> A random 4.9 GCC should be good enough for our purpose.

+1 due to above.

**Comment by jforissier** [comment]
Ping?

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
@vchong I take your +1 as an Acked-by: if you don't mind. Thanks.

**Comment by jbech-linaro** [comment]
Feel free to use one from me if needed (even though I had a comment).
`Acked-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
@jbech-linaro what comment? Is it:
> keep one sanity build using gcc4.9

?
With this patch, we **do** have one sanity build using GCC 4.9, it is the QEMU build done by Travis. The multi-platform build is done by Shippable and uses GCC 6.3.

**Comment by jbech-linaro** [comment]
> ?
> With this patch, we do have one sanity build using GCC 4.9, it is the QEMU build done by Travis. The multi-platform build is done by Shippable and uses GCC 6.3.

Yes, yes ... it is a single build, but going back and only doing a sanity build using that old version feels strange. If we look at it from the other end, we have had [build issues](https://github.com/jbech-linaro/optee_os/commit/9f91d3ec30939cdd1326f505b28e43f05a49ac82) when stepping up to later versions. I guess that would be just as interesting to catch here right away as catching build errors from an old version. So my choice here would be update GCC to 7.x. Do a first sanity build using 4.9, then do a sanity build where you also run xtest on 7.x. I.e., actually test and use latest and greatest, but I'm staring to see that pattern, I'm a bit alone on preferring that :) ... anyhow, Shippable covers this (build wise), so it's no big deal.

**Comment by jforissier** [comment]
Ah, got it. Yeah, we could do that also. Feel free to submit a patch on top of this one ;-)
