### ISSUE TITLE
error: missing braces around initializer

### ISSUE THREAD

**Issue by vchong** [OP-TEE/optee_os#1998]
Hi,

I'm getting below error (false positive) not just with android 4.9 but also linaro 4.9 toolchains.

```
core/tee/tadb.c:593:15: error: missing braces around initializer [-Werror=missing-braces]
  const struct tadb_entry null_entry = { 0 };
               ^
core/tee/tadb.c:593:15: error: (near initialization for ‘null_entry.prop’) [-Werror=missing-braces]
```

For android, we're using below workaround:
```
diff --git a/core/tee/tadb.c b/core/tee/tadb.c
index 6466825d..e9edfc96 100644
--- a/core/tee/tadb.c
+++ b/core/tee/tadb.c
@@ -590,7 +590,13 @@ err:
 
 TEE_Result tee_tadb_ta_delete(const TEE_UUID *uuid)
 {
-       const struct tadb_entry null_entry = { 0 };
+       const struct tadb_entry null_entry =
+               {{{0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}}, 0, 0, 0},
+               0,
+               {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
+               {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
+               {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
+               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}};
```

Do you guys want to support 4.9 toolchains as well (if so how?), or just call it a compiler issue?

**Comment by jenswi-linaro** [comment]
It seems we need to add at least one regression build with a GCC 4.9 compiler to avoid these errors.
I'd prefer:
```
const struct tadb_entry null_entry = { { { 0 } } };
```

**Comment by vchong** [comment]
Ok. Thanks! Will submit PR.

**Comment by jforissier** [comment]
> It seems we need to add at least one regression build with a GCC 4.9 compiler to avoid these errors.

Yeah. How about using 4.9 in `.travis.yml` (that's the QEMU build + xtest), while we keep `.shippable.yml` (the multi-platform builds) on a more up-to-date version (6.3)?

**Comment by jenswi-linaro** [comment]
Sounds good to me.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/2000

**Comment by vchong** [comment]
#2004

**Comment by vchong** [comment]
Patches merged.
