### ISSUE TITLE
allmodconfig fails to build on 4.4 topic branch

### ISSUE THREAD

**Issue by murpdj72** [OP-TEE/optee_os#1027]
When building the 4.4 OPTEE topic branch allmodconfig fails to build for
allmodconfig
	 ../mm/slub.c:3615:17: error: 'struct kmem_cache' has no member named 'red_left_pad'
	 ../mm/slub.c:3617:14: error: 'struct kmem_cache' has no member named 'red_left_pad'
	 make[2]: *** [mm/slub.o] Error 1

This is a result of commit 3ad78bad4fd43467f1fc6dff63076789b30c116b

Wondering if there is a follow up patch to fix this issue

**Comment by jforissier** [comment]
What is the "4.4 OPTEE topic branch"? What is commit 3ad78bad4fd43467f1fc6dff63076789b30c116b?

**Comment by vchong** [comment]
Think this is a kernel question.
http://git.linaro.org/kernel/linux-linaro-stable.git/shortlog/refs/heads/v4.4/topic/optee

However, 3ad78bad4fd43467f1fc6dff63076789b30c116b appears to be in linux-linaro-lsk-v4.4 only, not 4.4 optee topic branch. Wrong checkout?

**Comment by jbech-linaro** [comment]
I'm pretty sure he is talking about LSK4.4, since that is what Dan (TI) would like to use. The error message though, doesn't seem to have much to with the TEE driver(?).
@jenswi-linaro, you are the one that puts the patches on the LSK branch, have you seen the issue Daniel is facing?

**Comment by jbech-linaro** [comment]
I think @vchong comment is the question to answer, i.e, wrong checkout?
```
$ git branch -a --contains 3ad78bad4fd43467f1fc6dff63076789b30c116b
  remotes/lsk/linux-linaro-lsk-v4.4
  remotes/lsk/linux-linaro-lsk-v4.4-android-test
  remotes/lsk/linux-linaro-lsk-v4.4-rt-test
  remotes/lsk/linux-linaro-lsk-v4.4-test
  remotes/lsk/v4.4/topic/mm-kaslr-pax_usercopy
```
I.e, the commit Dan refers to isn't even in the `remotes/lsk/v4.4/topic/optee` branch.

**Comment by jenswi-linaro** [comment]
@jbech-linaro, no I haven't seen that before.

**Comment by murpdj72** [comment]
All
Yes after looking at the git log this came from the LSK 4.4 branch not OPTEE branch.  I will file an issue with the LSK team.  It looks like Alex Shi cherry picked this commit into the Linaro LSK branch.  So at the least be on the look out for this build issue.

Dan
